### ISSUE TITLE
Auto lock vault

### ISSUE THREAD

**Issue by akd2017** [cryptomator/cryptomator-win#6] opened 2017-11-21 12:04 UTC
can cryptomator provide auto lock of vault after a certain period of inactivity (even forced autounmount) these features are present in True crypt and veracrypt  i am using windows 10 on pc

**Comment by tobihagemann** [comment] 2017-11-21 13:13
Duplicate of cryptomator/cryptomator#274

**Closed as completed by tobihagemann** 2017-11-21 13:13 UTC
